### ISSUE TITLE
CmajPlugin doesn't scan in Ableton Live

### ISSUE THREAD

**Issue by remaininlight** [cmajor-lang/cmajor#32]
I can't seem to get the CmajPlugin (https://github.com/SoundStacks/cmajor/tree/main/tools/CmajPlugin) scanning in Ableton Live? Not sure if it's my setup (?) but other JUCE plugins work fine for me. If you have any ideas what it might be to do with or how to debug it I'm happy to take a look

**Comment by julianstorer** [comment]
Thanks for the heads-up Mark - I don't have Ableton installed at the moment to try it, so any clues as to what's going wrong would be appreciated!

**Comment by remaininlight** [comment]
This doesn't seem to be related to a previous Ableton VST3 error to do with code signing (it happens with latest version of JUCE, including the fix):
https://forum.juce.com/t/ableton-does-not-recognize-vst-after-updating-to-juce-7-0-8/58571/14

Someone else is experiencing a similar error on a non-Cmajor project, looks like this error is probably not Cmajor related:
https://forum.juce.com/t/vst3-plugin-not-visible-in-daw/45691/15?u=remaininlight

**Comment by julianstorer** [comment]
Do we know if this is a real issue or not? Can I close this issue..?

**Comment by remaininlight** [comment]
It's a real issue, but not with Cmajor. Closing it in this repo sounds good
