### ISSUE TITLE
ONNX != OnnxRuntime

### ISSUE THREAD

**Issue by olilarkin** [cmajor-lang/cmajor#34]
Noticed a mistake in the docs here:

https://github.com/cmajor-lang/cmajor/blob/e94e46d4cbc9d1f18d534e2952e2ddc728c8dcb8/docs/Cmaj%20Inference.md?plain=1#L5C1-L6C1

**Comment by julianstorer** [comment]
OK.. this is quite nuanced, but your point is that it's not correct to refer to ONNX as an engine, but as a format?

**Comment by julianstorer** [comment]
OK ta, will clarify..
