### ISSUE TITLE
Creating a GUI Patch Project example does not show the custom GUI in VSCode when run

### ISSUE THREAD

**Issue by teotigraphix** [cmajor-lang/cmajor#36]
Was just messing around trying to figure this out, I had installed the new CMajor Tools VSCode extension and realized by looking at the current examples of CustomGUI in github;

https://github.com/cmajor-lang/cmajor/blob/main/examples/patches/CustomGUI/demo_ui/index.js

`window.customElements.define ("VIEWDemoGUI", DemoGUI_View);`

needs to be this:

`window.customElements.define ("demo-patch-view", DemoGUI_View);`

Where `demo-patch-view` is the new id selector.

in the VSCode project generator.

**Comment by cesaref** [comment]
Good spot - the problem was in the order of some substitutions in the js action. I've got a fix for this which will be deployed with the next VSCode update
