### ISSUE TITLE
Compilation errors on Linux

### ISSUE THREAD

**Issue by dstrub18** [cmajor-lang/cmajor#40]
Hey Jules & Ces!
Thank you for open-sourcing cmajor!
I get some compiler errors when compiling according to the readme instructions on arch-linux.
`uname -r`: 6.7.6-arch1-1
`gcc --version`: 13.2.1 20230801

___

The errors mostly come from the graphviz dependency. However, it is also reporting some possibly dangling references in `cmaj_LLVMPerformer`.
I figured it's mostly warnings being treated as errors, but as the compilation fails when just following the readme instructions, I thought I should report this.
I've attached the output logs from ninja in this issue.
Thanks in advance!

[ninja-output-log.txt](https://github.com/cmajor-lang/cmajor/files/14607172/ninja-output-log.txt)

**Comment by cesaref** [comment]
Thanks for reporting this - we've been building with GCC 11.1. I'll try and recreate here with a more recent compiler

**Comment by cesaref** [comment]
There's now a fix in place for this

**Comment by dstrub18** [comment]
Thanks Ces! It fixed most compilation errors, but there are still errors coming from Graphviz. I guess there's no way other than patching up Graphviz itself?

Logs attached here: 
[logs-ninja.txt](https://github.com/cmajor-lang/cmajor/files/14633034/logs-ninja.txt)

**Comment by vitreo12** [comment]
Getting the same Graphviz errors here on 6.8.2-arch2-1 and gcc version 13.2.1
