### ISSUE TITLE
Xcode project doesn't build

### ISSUE THREAD

**Issue by MarcusTomlinson** [cmajor-lang/cmajor#41]
<img width="1512" alt="Screenshot 2024-03-15 at 13 18 06" src="https://github.com/cmajor-lang/cmajor/assets/7335138/00f3e8c6-3f30-42c3-856e-fa667a9cb7cf">

**Comment by julianstorer** [comment]
Hi - we fixed this one yesterday, pull the latest version and try again!

**Comment by MarcusTomlinson** [comment]
```
MacBook-Pro-2:cmajor marcustomlinson$ git pull
Already up to date.
```

**Comment by julianstorer** [comment]
Make sure your subrepos are up to date, that file is in the choc subrepo
