### ISSUE TITLE
CmajPlugin not included in released Win binaries.

### ISSUE THREAD

**Issue by ZonderP** [cmajor-lang/cmajor#43]
According to
https://cmajor.dev/docs/GettingStarted#loading-patches-in-your-daw-with-the-cmajor-vstau-plugin
the CmajPlugin should be included in the released binaries.
But it seems not to be in the last 3 released versions of  'cmajor_win_x64.exe'.
This installer for Windows for me just installs the cmd-line tool cmaj.exe, the CmajPerformer.dll and some example patches.
Seems also not to be contained in the binaries for Linux, but I found it's name in the MacOS binaries.

**Comment by cesaref** [comment]
We moved some files around, and it looks like the windows installer builder has been failing silently for this. I'll see about a fix. Thanks for pointing this out!

**Comment by ZonderP** [comment]
Oh my, it indeed gets properly installed to 'Program Files\Common Files\VST3'.
I was fooled by someone on KVR, who insisted that
a) 'CmajPerformer.dll' was the plugin (although I wondered, why it would be VST2 - and found out on cmajor.dev, that it would be a redistributable binary) and
b) it would be installerd to 'Program Files\cmajor\cmajor'.

For those reasons, it didn't come to my mind to look into the standard VST3 installation folder - sorry, my bad.
All good regarding Windows binaries - the plugin is there where it is supposed to be.

Thanks for your help
