### ISSUE TITLE
cmajor vst3 plugin as effect instead of instrument

### ISSUE THREAD

**Issue by llalundo** [cmajor-lang/cmajor#52]
I just wonder if this is the intended behaviour or if something could be done about this. When I use the available cmajor vst3 plugin on Mac in my DAW of preference (Reason 12) it is added as an effect and not as an instrument.

Would it be possible to have the vst3 plugin to be created so it's recognized as an instrument, not as an effect?

**Comment by julianstorer** [comment]
Yep, we're obviously aware of this - it's annoying that some hosts treat instruments and effects differently, but it's not possible to know which type the plugin should be before it's loaded. We'll figure out a workaround before too long, maybe a couple of different wrapper plugins that are set up as different types.
