### ISSUE TITLE
Changes are not applied dynamically when the patch file is saved

### ISSUE THREAD

**Issue by giohappy** [cmajor-lang/cmajor#54]
If I'm not wrong, when a `cmajor` patch file is saved while running (either with the VSCode extension or with `cmaj play`) the changes should be recompiled and applied on the fly. This is not working for me. I need to stop the running patch and rerun it.

I'm on Windows 11 with the latest release ([1.0.2416](https://github.com/cmajor-lang/cmajor/releases/tag/1.0.2416)) for Windows.

**Comment by cesaref** [comment]
Hi, this is a known bug that crept in to the latest release. This has been fixed and i'll get a fixed release pushed out shortly.

**Comment by cesaref** [comment]
The update is now available

**Comment by giohappy** [comment]
Just to confirm that it works fine now. Thanks!
