### ISSUE TITLE
PatchWorker example crashses in Reaper and Bitwig

### ISSUE THREAD

**Issue by giohappy** [cmajor-lang/cmajor#55]
I'm not sure if the `PatchWorker` example is supposed to work when executed inside the Cmaj VST plugin, but as soon as I load the patch inside either Reaper or Bitwig the plugin crashes.

**Comment by julianstorer** [comment]
Ah, thanks for the heads-up, we'll investigate..

**Comment by giohappy** [comment]
Windows 11

**Comment by julianstorer** [comment]
Can you give it another shot with the latest build? Can't really reproduce this, but have fixed some other stuff that might be relevant..

**Comment by giohappy** [comment]
Tested on another PC (Windows 11) wirh version [1.0.2436](https://github.com/cmajor-lang/cmajor/releases/tag/1.0.2436) and it works fine.
I will test again later on the PC that was giving problems

**Comment by julianstorer** [comment]
OK thanks. We're actively working on the plugin stuff at the moment, there'll be a lot of fixes and releases coming out in the next few weeks anyway
