### ISSUE TITLE
Web view content doesn't load with local builds of JUCE plugins with custom UIs

### ISSUE THREAD

**Issue by giohappy** [cmajor-lang/cmajor#58]
Just for the record, I'm reporting here an issue we were chatting about on Discurse regarding an issue I'm experiencing with local builds of the HYCE plugin.

@cesaref has done some fixes recently to the JUCE plugin to solve a problem with the state of the webview on first load.
He passed me the VST3 and standalone binaries for the CutomGUI example patch, and they work fine.

However, builds done my be on different machines, and by a collegue of mine, with the same cmajor [1.0.2444](https://github.com/cmajor-lang/cmajor/releases/tag/1.0.2444) are not working. 
In the case of CustomGUI I see an empty black panel (it's a webview since I can see the contextual menu).
With Pro54 instead I get the usual grey panel of JUCE, with the JUCE logo.

I've built the CutomGUI with the DevTools option enabled. By inspecting the console log I see the following error reported:

`Uncaught (in promise) SyntaxError: Invalid or unexpected token (index.js:94)`.

Indeed, the [createPatchView](https://github.com/cmajor-lang/cmajor/blob/6e561c1b3001ee65213aa51ba153600027fde26c/include/cmajor/helpers/cmaj_PatchWebView.h#L210) promise is never fullfilled (console logs placed inside it do not print).

Maybe the js file included in the compiled binary is somehow corrupted? I don't know...

The only  reason I can think of for such a diffence could be the build tools. We're using `Visual Studio 17 2022` with `MSVC v143` and `Windows 11 SDK 10.0.22621.0`.

**Comment by julianstorer** [comment]
We're trying to reproduce this, but just as a sanity-check:
The error you're seeing at index.js:94 is at the *end* of the file, and an invalid token there sounds to me like you've got some junk appended to that file. Can you double check you've not inserted something there by mistake?

**Comment by giohappy** [comment]
If it can be useful here it is an extract from the _rdata sections of a working vst3 (@cesaref) and mine, around the end of the end `index.js` text

working:
![image](https://github.com/cmajor-lang/cmajor/assets/571129/8605c010-fc7b-49bc-aeb5-eb3a43fc463f)

mine:
![image](https://github.com/cmajor-lang/cmajor/assets/571129/8a33cd62-6ba5-4c53-a981-660e0e7b0dcb)

They look pretty similar, except the memory offsets

**Comment by giohappy** [comment]
Another evidence of the problem loading the patch.

This is loading the patch with the Cmajor plugin:
![image](https://github.com/cmajor-lang/cmajor/assets/571129/d37e48bc-f920-49aa-976c-f797061e7361)

This is my build (missing source code for `demo_ui/index.js`):
![image](https://github.com/cmajor-lang/cmajor/assets/571129/62e5f78d-5835-4bab-a630-066dd9295d62)

**Comment by giohappy** [comment]
Notice that, apparently, the string view lenght for `index.js` inside `cmajor_plugin.cpp` is different from the one reported by @cesaref.

@cesaref 
```cpp
    static constexpr std::array files =
    {
        File { "cmaj_api/cmaj-patch-connection.js", std::string_view (cmaj_api_cmajpatchconnection_js, 12712) },
        File { "Freeverb_CustomGUI.cmajorpatch", std::string_view (Freeverb_CustomGUI_cmajorpatch, 436) },
        File { "cmaj_api/assets/cmajor-logo.svg", std::string_view (cmaj_api_assets_cmajorlogo_svg, 2913) },
        File { "cmaj_api/cmaj-audio-worklet-helper.js", std::string_view (cmaj_api_cmajaudioworklethelper_js, 27963) },
        File { "cmaj_api/cmaj-event-listener-list.js", std::string_view (cmaj_api_cmajeventlistenerlist_js, 3474) },
        File { "cmaj_api/cmaj-generic-patch-view.js", std::string_view (cmaj_api_cmajgenericpatchview_js, 6186) },
        File { "cmaj_api/cmaj-midi-helpers.js", std::string_view (cmaj_api_cmajmidihelpers_js, 13253) },
        File { "cmaj_api/cmaj-parameter-controls.js", std::string_view (cmaj_api_cmajparametercontrols_js, 29343) },
        File { "cmaj_api/cmaj-patch-view.js", std::string_view (cmaj_api_cmajpatchview_js, 4941) },
        File { "cmaj_api/cmaj-piano-keyboard.js", std::string_view (cmaj_api_cmajpianokeyboard_js, 15540) },
        File { "cmaj_api/cmaj-server-session.js", std::string_view (cmaj_api_cmajserversession_js, 18844) },
        File { "demo_ui/index.js", std::string_view (demo_ui_index_js, 3384) }
    };
```

mine:
```cpp
    static constexpr std::array files =
    {
        File { "cmaj_api/cmaj-patch-connection.js", std::string_view (cmaj_api_cmajpatchconnection_js, 12712) },
        File { "Freeverb_CustomGUI.cmajorpatch", std::string_view (Freeverb_CustomGUI_cmajorpatch, 436) },
        File { "cmaj_api/assets/cmajor-logo.svg", std::string_view (cmaj_api_assets_cmajorlogo_svg, 2913) },
        File { "cmaj_api/cmaj-audio-worklet-helper.js", std::string_view (cmaj_api_cmajaudioworklethelper_js, 27963) },
        File { "cmaj_api/cmaj-event-listener-list.js", std::string_view (cmaj_api_cmajeventlistenerlist_js, 3474) },
        File { "cmaj_api/cmaj-generic-patch-view.js", std::string_view (cmaj_api_cmajgenericpatchview_js, 6186) },
        File { "cmaj_api/cmaj-midi-helpers.js", std::string_view (cmaj_api_cmajmidihelpers_js, 13253) },
        File { "cmaj_api/cmaj-parameter-controls.js", std::string_view (cmaj_api_cmajparametercontrols_js, 29343) },
        File { "cmaj_api/cmaj-patch-view.js", std::string_view (cmaj_api_cmajpatchview_js, 4941) },
        File { "cmaj_api/cmaj-piano-keyboard.js", std::string_view (cmaj_api_cmajpianokeyboard_js, 15540) },
        File { "cmaj_api/cmaj-server-session.js", std::string_view (cmaj_api_cmajserversession_js, 18844) },
        File { "demo_ui/index.js", std::string_view (demo_ui_index_js, 3477) }
    };
```

**Comment by giohappy** [comment]
@julianstorer @cesaref I got it working by changin 3477 to 3384 in `File { "demo_ui/index.js", std::string_view (demo_ui_index_js, 3477) }`.
No idea why, but with this "magic" value the UI loads up fine.

**Comment by giohappy** [comment]
Iive applied the pathc proposed by @julianstorer 

```diff
diff --git a/modules/compiler/include/cmaj_CppGenerationUtils.h b/modules/compiler/include/cmaj_CppGenerationUtils.h
index c31ea69..94f8044 100644
--- a/modules/compiler/include/cmaj_CppGenerationUtils.h
+++ b/modules/compiler/include/cmaj_CppGenerationUtils.h
@@ -107,9 +107,7 @@ namespace cmaj::cpp_utils
             }
         }

-        std::ostringstream s;
-        s << "R\"" << guard << "(" << text << ")" << guard << "\"";
-        return s.str();
+        return "R\"" + guard + "(" + std::string(text) + ")" + guard + "\"";
     }
```

but apparently it doesn't solve the issue with the size. You can see me step debugging in the screenshot below:

![image](https://github.com/cmajor-lang/cmajor/assets/571129/b927db64-354b-4bf5-b286-77f6008aea88)

**Comment by giohappy** [comment]
After removing the `CR` characters from index.js the size was calculated correctly.

**Comment by giohappy** [comment]
@cesaref apparently the problem seems gone with your latest fixes. I will close the issue for the moment and I will keep testing the next week.
