### ISSUE TITLE
Updating cmajor creates a duplicate entry in PATH (Environment Variables)

### ISSUE THREAD

**Issue by Olnium** [cmajor-lang/cmajor#68]
Per title, updating is causing a duplicate entry in PATH, causing it to exceed maximum allowed characters over time. Workaround is to delete dupes as they occur.

**Comment by cesaref** [comment]
Ah, the windows installer I take it? I imagine the problem is that the uninstall is not removing the path that was added, i'll take a look. Thanks for the report!

**Comment by Olnium** [comment]
Yes. Apologies, I should have mentioned I'm on Windows. Thanks!

**Comment by cesaref** [comment]
I've updated the windows installer generator to resolve this issue. It is available in the latest pre-release, https://github.com/cmajor-lang/cmajor/releases/tag/1.0.2582

**Comment by Olnium** [comment]
Confirmed fixed with latest build.
