### ISSUE TITLE
Compiler error in generated C++ code when targeting certain platforms

### ISSUE THREAD

**Issue by JamesHallowell** [cmajor-lang/cmajor#76]
Hi,

I'm trying to compile the generated C++ code for a CMajor patch to run on a [Daisy Seed](https://electro-smith.com/products/daisy-seed), but hitting a compile error when it tries to call the `max` intrinsic in the code generated from `std::smoothing::SmoothedValue::setTarget`:

![image](https://github.com/user-attachments/assets/22bdfc7c-1763-4b0c-b308-fb4b76fd05ef)

It appears on this platform `int32_t` is a `long` not an `int`. Is this something that could reasonably be accomodated for in the generated code? Potentially wrapping `int32` constants like `int32_t {1}`? [It appears something similiar is already in place for `int64`](https://github.com/cmajor-lang/cmajor/blob/3bbdce9d8638a7d3625c73505486b86704858b3e/modules/compiler/src/backends/CPlusPlus/cmaj_CPlusPlusGenerator.cpp#L1498-L1499).

Thanks.

**Comment by cesaref** [comment]
Thanks for the feedback. I'll look to see what can be done about this.,

**Comment by cesaref** [comment]
I've gone with this suggestion. I had a look at a different option, to actually use specialisations but I think this is a better compromise. Let me know if it resolves your problem. A build hasn't been released, but it is an update to the source code for the c++ generator

**Comment by JamesHallowell** [comment]
> I've gone with this suggestion. I had a look at a different option, to actually use specialisations but I think this is a better compromise. Let me know if it resolves your problem. A build hasn't been released, but it is an update to the source code for the c++ generator

Thanks @cesaref, just tried that out and it works great! Much appreciated.
