### ISSUE TITLE
Inter-plugin-communication 

### ISSUE THREAD

**Issue by metakeule** [cmajor-lang/cmajor#81]
Sorry for the messy title, please change it, if you have a better name....

I want to have several instances of the same CLAP or VST plugin that coordinate with each other (e.g. like SMART EQ4). How would I do this?

**Comment by 0xchase** [comment]
This doesn't sound like an issue specific to cmajor. There are various existing [javascript IPC libraries](https://www.npmjs.com/package/node-ipc) you could look into.
